// ============================================================================
// USER TYPES
// ============================================================================
// Matches PostgreSQL public.users table and Supabase auth.users

export enum UserRole {
  UNDERGRAD = "undergrad",
  GRADUATE = "graduate",
  ADMIN = "admin",
}

/**
 * Volunteer-specific roles for event signups
 * These determine capacity constraints
 */
export enum VolunteerRole {
  SCRIBE = "scribe", // 1 max, then waitlist
  GRADUATE = "graduate", // 2-3, then waitlist
  PRECEPTOR = "preceptor", // 2 max, hard cap
  OUTREACH_MANAGER = "outreach_manager", // 2 max, hard cap
  DENTAL_STUDENT = "dental_student", // 2 max, hard cap
}

/**
 * Complete user object (what you get from the database)
 *
 * - id: Supabase auth UUID
 * - email: Required for login
 * - role: Determines permissions (volunteer vs admin)
 * - Optional fields: Users might not fill out phone/major immediately
 */
export type User = {
  id: string; // UUID from Supabase auth
  email: string; // Must be @uw.edu
  name: string;
  role: UserRole;
  phone?: string; // Optional: for SMS notifications
  year?: string; // e.g., "Junior", "1st year grad"
  major?: string; // e.g., "Biology"
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
};

/**
 * Data needed to CREATE a new user (signup form)
 *
 * WHY SEPARATE FROM User?
 * - User has id/timestamps (generated by database)
 * - CreateUserData is what the FRONTEND sends
 * - Keeps your forms clean: only ask for what you need
 */
export type CreateUserData = {
  email: string;
  password: string; // Only needed at creation (Supabase hashes it)
  name: string;
  role: UserRole;
  phone?: string;
  year?: string;
  major?: string;
};

/**
 * Data for UPDATING a user profile
 *
 * WHY ALL OPTIONAL?
 * - PATCH requests: only send fields you're changing
 * - Example: User only wants to update phone number
 */
export type UpdateUserData = {
  name?: string;
  phone?: string;
  year?: string;
  major?: string;
};
